In [1]:
import os
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
training_data = pd.read_excel (r"C:\Users\MCSL-user\OneDrive\Data Sets for Machine Learning\Data Acquired - Sensor\Training_Data_First.60(F)_Last.60(N).xlsx") #gets the data from PC
training_data.head() #Displays data - First 60% Drift fault - Last 60% Normal Data 

Max    Mean  Label
0  49.9  31.525      0
1  49.9  31.521      0
2  49.8  31.481      0
3  49.9  31.499      0
4  49.9  31.525      0

In [3]:
X_train = training_data[['Max','Mean']]
y_train = training_data[['Label']]

In [4]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0, max_depth=2)
clf.fit(X_train, y_train.values.ravel()) #.ravel() func. accepts values as 2D as 1D was expected by the model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [5]:
testing_data = pd.read_excel (r"C:\Users\MCSL-user\OneDrive\Data Sets for Machine Learning\Data Acquired - Sensor\Testing_Data_First.40(F)_Last.40(N).xlsx")
testing_data.head()

Max    Mean  Label
0  49.6  31.279      0
1  49.7  31.323      0
2  49.7  31.325      0
3  49.7  31.325      0
4  49.6  31.259      0

In [6]:
X_test = testing_data[['Max','Mean']]
y_test = testing_data[['Label']]

In [7]:
clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [8]:
clf.score(X_test, y_test)

1.0

In [9]:
y_pred = clf.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[40  0]
 [ 0 40]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        40

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [11]:
# Now we are gonna use Pickle or Joblib API which actually helps in not training the model each time we run the program.
import pickle

with open('DT_Trained_Code_FaultDetection_PICKLE','wb') as f: #wb=write binary
    pickle.dump(clf,f)

In [12]:
with open('DT_Trained_Code_FaultDetection_PICKLE','rb') as f:
    DT_prediction = pickle.load(f)

In [13]:
DT_prediction.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [14]:
DT_prediction.score(X_test, y_test)

1.0