In [1]:
import os
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

training_data = pd.read_excel (r"C:\Users\MCSL-user\OneDrive\Data Sets for Machine Learning\Data Acquired - Sensor\Training_Data_First.60(F)_Last.60(N).xlsx") #gets the data from PC

X_train = training_data[['Max','Mean']]
y_train = training_data[['Label']]

In [2]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
#Create a Gaussian Classifier
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(X_train, y_train.values.ravel())

GaussianNB(priors=None, var_smoothing=1e-09)

In [3]:
testing_data = pd.read_excel (r"C:\Users\MCSL-user\OneDrive\Data Sets for Machine Learning\Data Acquired - Sensor\Testing_Data_First.40(F)_Last.40(N).xlsx")

X_test = testing_data[['Max','Mean']]
y_test = testing_data[['Label']]

gnb.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [4]:
gnb.score(X_test, y_test)

1.0

In [5]:
y_pred = gnb.predict(X_test)

In [6]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [7]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[40  0]
 [ 0 40]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        40

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [8]:
# Now we are gonna use Pickle or Joblib API which actually helps in not training the model each time we run the program.
import pickle

with open('Naive_Bayes_Trained_Code_FaultDetection_PICKLE','wb') as f: #wb=write binary
    pickle.dump(gnb,f)
    
with open('Naive_Bayes_Trained_Code_FaultDetection_PICKLE','rb') as f:
    NaiveBayes_prediction = pickle.load(f)
    
NaiveBayes_prediction.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [9]:
NaiveBayes_prediction.score(X_test, y_test)

1.0